Develop main functions
AlexOdnoshivkin/java-explore-with-me pull request #1
Opened 2022-11-13 22:20 UTC by AlexOdnoshivkin

2022-11-28 03:52 UTC, AlexOdnoshivkin commented
Тестов и Javadoc планируется добавить позднее, так как прямо сейчас уже времени мало. Требования ТЗ выполнены.

2022-11-28 16:37 UTC, damirovna requested changes
Сейчас я проверила:

Работа со сборкой
работа с докером
струтуры БД
модель данных
Объектов DTO
**Нужно исправить работу с просмотрами и внести правки в модель и объекты DTO не только для события, но и аналогично для всех сущностей.**

2022-11-28 16:37 UTC, damirovna commented on ewm-service/src/main/resources/schema.sql
> +    CONSTRAINT pk_categories PRIMARY KEY (id)
Нужно добавить:
CONSTRAINT UQ_CATEGORY_NAME UNIQUE (name)

2022-11-28 16:37 UTC, damirovna commented on ewm-service/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS events (
Практически все поля в этой таблице должны быть NOT NULL

2022-11-28 16:37 UTC, damirovna commented on ewm-service/src/main/resources/schema.sql
> +    views INTEGER,
Просмотры должны быть получены из сервиса статистики, в базе основного сервиса поля views быть не должно

2022-11-28 16:37 UTC, damirovna commented on ewm-service/src/main/resources/schema.sql
> +    CONSTRAINT fk_requester FOREIGN KEY (requester) REFERENCES users(id)
Нужно добавить CONSTRAINT UQ_PARTICIPANT_PER_EVENT UNIQUE (requester, event)

2022-11-28 16:37 UTC, damirovna commented on pom.xml
>  <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
Отличная работа со сборкой!

2022-11-28 16:37 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/ewmservice/models/event/Event.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
В этом классе и в остальных классах модели укажите, пожалуйста https://github.com/column(nullable = false) на полях, которые не могут быть null

2022-11-28 16:37 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/ewmservice/models/event/dto/EventShortDto.java
> +public class EventShortDto {
Обратите внимание, что все поля этого класса дублируются в классе EventFullDto используйте наследование, чтобы избежать дублирования кода

2022-11-28 16:37 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/ewmservice/models/event/dto/EventShortDto.java
> +public class EventShortDto {
Нужно добавить во все DTO классы:
1) аннотации @NotBlank на все строковые обязательные поля 
2)аннотации @ NotNull на все остальные обязательные поля  
3) аннотации @PositiveOrZero на поля в которых не может быть отрицательного значения, например просмотры, количество участников, максимальное количество участников и т.д.
4) аннотацию @Future на дату нового события

2022-11-28 16:37 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/ewmservice/models/event/dto/UpdateEventRequest.java
> +    private String title;
Этому полю нужно добавить ограничения на размер:
```
@Size(min = 3, max = 120)
	private final @Nullable String title;
```

Аналогично нужно ограничить соответствующими им значениями поля: description и annotation

2022-11-28 20:24 UTC, AlexOdnoshivkin commented
Спасибо за обратную связь! Работа по замечаниям:
1. Исправил таблицы.
2. Поправил аннотации в классах Dto.
3. По поводу класса EventFullDto. Я пока оставил его без наследования, потому-что некоторые поля имеют отличающиеся тип данных(category, iniciator), а некоторые вовсе там не нужны. Мне кажется так будет проще реализация и лучше читаемость, хоть и ценой некоторых повторений. Если вы настаиваете -  сделаю с наследованием, подумаю как можно лучше это сделать.
4. Исправил логику работы с views. Убрал поле из бд основного сервиса, добавил запрос и обработку views в методы поиска событий.

2022-11-29 16:41 UTC, damirovna approved these changes
Критических замечаний нет, работу принимаю.

2022-11-29 16:41 UTC, damirovna commented on stats-server/src/main/resources/schema.sql
> +    app VARCHAR(255),
Это поле должно быть уникальным

2022-11-30 16:57 UTC, merged